# Generated by Django 3.2.7 on 2021-11-08 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0002_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotesGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizer.class')),
            ],
        ),
        migrations.AddField(
            model_name='notes',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizer.notesgroup'),
            preserve_default=False,
        ),
    ]
