# Generated by Django 3.2.7 on 2021-11-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0003_auto_20211108_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
