# Generated by Django 3.2.7 on 2021-11-10 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0004_notes_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizer.student'),
            preserve_default=False,
        ),
    ]
