# Generated by Django 3.2.7 on 2021-11-12 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0006_remove_student_pref_cal_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizer.student'),
            preserve_default=False,
        ),
    ]
