# Generated by Django 3.2.7 on 2021-11-28 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0009_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sections',
            field=models.ManyToManyField(to='organizer.Section'),
        ),
    ]
