# Generated by Django 3.2.7 on 2021-11-29 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0010_student_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='section_id',
            field=models.CharField(max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
