# Generated by Django 3.2.7 on 2021-12-01 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0011_section_section_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='notesgroup',
            name='create_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
